language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: mugil.cepahalus+npmjs.com@gmail.com
  on:
    tags: true
  api_key:
    secure: b4e538ffgK7DjBchdE7vtVTpZvjMdDAWOwpXwnFd1uFrPygo07ldskswAgmbiprhs9B96lu04PUbg/T/OMQCq8eGJA8rJwI57OUC0iGy5tSyQk7wCKHJQQ/eNPiiwDJLS6uWAXhGe6GkelmMyrXHzpGQyPvqEt4RTMtt/uTgj9HHV6ddWFRlAjPn6ckWx8HDac5HW2IGdhdbSOoZWXAX7Rk15EwKwTgg17n5gpxrT+d8Brtay7P1V088JUc12CdNdIMOY6/PTmo2W03NAG0LY9JVBPJqsR1IuPArjJ81OLOW9y4M3gpyawj5C0GvrV49eX5drrrmvpbwWbbxuSFJGXyjdAfmoe0xi39El2yaJFPgQyP0qlk4P4JM52scHwvOivIZjXUvw1227tXvR51TwM6XmBduEbMiZ4rALxgGmTVI2PKbnbJKUWHpLbxdRywAuSkpBY2P/VJK9rYPCJqifHx8HLQ14trOEK6FFhLz4Ev/K/p1Kyt2HRYx883Xl+z/XSfwWqcmG9MiIktGciuN4qQIQVdbmY6bUEthFtVEckMINRlAaTj8xIbM+oU2b4jQoNE5IxPp4CNVmDG97iDNeEDA5IpC/wFoGS8OFO6Foy7jmc3RyCTCTogRtwaX/jiTtg/THOYRL1Cjg5im67UflkRIw4SvZSQGqpZ+FGHB8kM=
