language: node_js
node_js:
- '7'
deploy:
  provider: npm
  email: mugil.cepahalus+npmjs.com@gmail.com
  on:
    tags: true
  api_key:
    secure: THWxmU8zreESL8OuCICYX++wIzPr7M8b8IjyO9deQwdt5H+iSrXwsXCdEa3oB/x/Lg0dwHbzbUT8sY5/1Qgci1V5LX4GsH5kTOkLvatK3df0kPbcQ0aeUdF8XHk/skoMCJeWj704S0VJCfY4sf3ApIDDPTl3amQSJCAMN9wfh9uSMGaL2dU1BfRfDJR7zHWShqvYRtdhLN+YGhxcIZVGw2ODMD2wXQLSXNmYfr6BNMVGZnvAHe2OsiCRMAEYblmihqVE/2GsEdeoxjBKE6joFbgg6Zhd4dCG4uSBimpIR0npoyAB0xEQXKfE9A5yDH5FG3rezIQGhYMgBLnd5u9VQ22Jo089WfNosH/iIe83+g3YhhXWZZesinqDksaRgY7rpZRN0tCmoJkcRruUz1du3jjY+87pI8Ow1bG1yCTM1AJyTx/Qlo3oSd9+sN+Tw17FOPB8P8NJcIsKRSjqUO8oWHvbIKHQOj4bgkhLcsoi4GruWgfr0Te8i5Ao4zC7KMI2ON2GyL5PGm+xIhKNFIp663dWObMBP14kZuTE3ibM3ugs0T/nBbuTUB/opd5vQCD+CiLNbAaA4SF1sBh86xiYEjWvgv4QVo0WJ1cz2KZ+ST0jNITqV6OKf/klPvPylJi2UeOGSorsKnN9gZY6Z+ja/AXbVoDQzu8q8RKbqaDUBMc=
